import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :real_product_size_backend, RealProductSizeBackendWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Req

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# Do not print debug messages in production

# Configure file logging for production
config :logger,
  backends: [:console, {LoggerFileBackend, :info_log}, {LoggerFileBackend, :error_log}]

# Info log configuration (info, warn, error)
config :logger, :info_log,
  path: "./logs/info.log",
  level: :info,
  format: "$date $time $metadata[$level] $message\n",
  rotate: %{max_bytes: 10_485_760, keep: 10}  # 10MB files, keep 10

# Error log configuration (error only)
config :logger, :error_log,
  path: "./logs/error.log",
  level: :error,
  format: "$date $time $metadata[$level] $message\n",
  rotate: %{max_bytes: 10_485_760, keep: 20}  # 10MB files, keep 20

# Console logger (for production)
config :logger, :console,
  format: "$time $metadata[$level] $message\n",
  metadata: [:request_id],
  level: :warning  # Only show warnings and errors on console in prod

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
